project:
  type: website
  output-dir: docs
website:
  title: "Michael Montemurri"
  navbar:
    background: light
    right:
      - text: About 
        href: index.qmd
      - text: CV
        href: cv.qmd
      - text: Repositories
        href: repos.qmd

  page-footer:
    center:
      - text: <ins>Made with Quarto</ins>
        href: https://quarto.org
      - text: <ins>Source</ins>
        href: https://github.com/michaelmontemurri/michaelmontemurri.github.io
      - text: <ins>License</ins>
        href: ./LICENSE

format:
  html:

    theme:
      light: [simplex, styles/custom.scss]
      dark: [simplex, styles/custom_dark.scss]
    fontsize: 0.95em
    linestretch: 1.4
    mainfont: "sans-serif"
    toc: true
    toc-title: "<br><br><br>"
    link-external-newwindow: true
    #minimal: true
